export const appointments = [
    {
      id: 13,
      title: 'Plumbing Service',
      subtitle: 'Fix kitchen sink leak',
      time: '2 hrs ago',
      categoryId: '1',
      customerID: 'C001',
      customerName: 'John Doe',
      location: '123 Elm Street, Springfield',
      appointmentDate: '2024-08-25 14:00', 
    },
    {
      id: 14,
      title: 'Electrical Service',
      subtitle: 'Install ceiling fan',
      time: '4 hrs ago',
      categoryId: '2',
      customerID: 'C002',
      customerName: 'Jane Smith',
      location: '456 Oak Avenue, Springfield',
      appointmentDate: '2024-08-26 09:00', 
    },
    {
      id: 15,
      title: 'Cleaning Service',
      subtitle: 'Deep clean apartment',
      time: '6 hrs ago',
      categoryId: '3',
      customerID: 'C003',
      customerName: 'Alice Johnson',
      location: '789 Pine Road, Springfield',
      appointmentDate: '2024-08-27 11:00', 
    },
    {
      id: 16,
      title: 'Home Tutoring',
      subtitle: 'Maths session for 10th grade',
      time: '8 hrs ago',
      categoryId: '4',
      customerID: 'C004',
      customerName: 'Michael Brown',
      location: '101 Maple Drive, Springfield',
      appointmentDate: '2024-08-28 15:00',
    },
    {
      id: 17,
      title: 'Painting Service',
      subtitle: 'Paint living room walls',
      time: '1 day ago',
      categoryId: '5',
      customerID: 'C005',
      customerName: 'Emily Davis',
      location: '202 Birch Lane, Springfield',
      appointmentDate: '2024-08-29 10:00',
    },
    {
      id: 18,
      title: 'Gardening Service',
      subtitle: 'Trim hedges and mow lawn',
      time: '2 days ago',
      categoryId: '6',
      customerID: 'C006',
      customerName: 'David Wilson',
      location: '303 Cedar Circle, Springfield',
      appointmentDate: '2024-08-30 13:00',
    },
    {
      id: 19,
      title: 'Plumbing Service',
      subtitle: 'Unclog bathroom drain',
      time: '3 days ago',
      categoryId: '1',
      customerID: 'C007',
      customerName: 'Sophia Taylor',
      location: '404 Willow Street, Springfield',
      appointmentDate: '2024-08-31 16:00',
    },
    {
      id: 20,
      title: 'Electrical Service',
      subtitle: 'Fix power outlet',
      time: '5 hrs ago',
      categoryId: '2',
      customerID: 'C008',
      customerName: 'James Anderson',
      location: '505 Spruce Avenue, Springfield',
      appointmentDate: '2024-09-01 09:30',
    },
    {
      id: 21,
      title: 'Cleaning Service',
      subtitle: 'Clean windows and carpets',
      time: '1 day ago',
      categoryId: '3',
      customerID: 'C009',
      customerName: 'Olivia Martinez',
      location: '606 Fir Road, Springfield',
      appointmentDate: '2024-09-02 12:00',
    },
    {
      id: 22,
      title: 'Home Tutoring',
      subtitle: 'Physics session for 12th grade',
      time: '7 hrs ago',
      categoryId: '4',
      customerID: 'C010',
      customerName: 'Liam Hernandez',
      location: '707 Elm Street, Springfield',
      appointmentDate: '2024-09-03 14:30',
    },
    {
      id: 23,
      title: 'Painting Service',
      subtitle: 'Repaint kitchen cabinets',
      time: '4 days ago',
      categoryId: '5',
      customerID: 'C011',
      customerName: 'Mia Robinson',
      location: '808 Oak Avenue, Springfield',
      appointmentDate: '2024-09-04 11:00',
    },
    {
      id: 24,
      title: 'Gardening Service',
      subtitle: 'Plant new flower beds',
      time: '6 days ago',
      categoryId: '6',
      customerID: 'C012',
      customerName: 'Ethan Clark',
      location: '909 Pine Road, Springfield',
      appointmentDate: '2024-09-05 10:30',
    },
  ];
  