export const favorites = [
    {
      uid: 'U001',
      username: 'John Doe',
      profilePic: 'https://randomuser.me/api/portraits/men/1.jpg',
      email: 'john.doe@example.com',
      categoryID: '1',
      categoryName: 'Plumber',
      totalRating: 4.8,
      totalAgreements: 125,
    },
    {
      uid: 'U003',
      username: 'Alice Johnson',
      profilePic: 'https://randomuser.me/api/portraits/women/2.jpg',
      email: 'alice.johnson@example.com',
      categoryID: '3',
      categoryName: 'Maid',
      totalRating: 4.7,
      totalAgreements: 98,
    },
    {
      uid: 'U004',
      username: 'Michael Brown',
      profilePic: 'https://randomuser.me/api/portraits/men/2.jpg',
      email: 'michael.brown@example.com',
      categoryID: '4',
      categoryName: 'Home Tutor',
      totalRating: 4.9,
      totalAgreements: 167,
    },
    {
      uid: 'U005',
      username: 'Emily Davis',
      profilePic: 'https://randomuser.me/api/portraits/women/3.jpg',
      email: 'emily.davis@example.com',
      categoryID: '5',
      categoryName: 'Painter',
      totalRating: 4.6,
      totalAgreements: 112,
    },
    {
      uid: 'U007',
      username: 'Sophia Taylor',
      profilePic: 'https://randomuser.me/api/portraits/women/4.jpg',
      email: 'sophia.taylor@example.com',
      categoryID: '1',
      categoryName: 'Plumber',
      totalRating: 4.7,
      totalAgreements: 154,
    },
    {
      uid: 'U008',
      username: 'James Anderson',
      profilePic: 'https://randomuser.me/api/portraits/men/4.jpg',
      email: 'james.anderson@example.com',
      categoryID: '2',
      categoryName: 'Electrician',
      totalRating: 4.8,
      totalAgreements: 132,
    },
    {
      uid: 'U009',
      username: 'Olivia Martinez',
      profilePic: 'https://randomuser.me/api/portraits/women/5.jpg',
      email: 'olivia.martinez@example.com',
      categoryID: '3',
      categoryName: 'Maid',
      totalRating: 4.9,
      totalAgreements: 175,
    },
    {
      uid: 'U012',
      username: 'Ethan Clark',
      profilePic: 'https://randomuser.me/api/portraits/men/6.jpg',
      email: 'ethan.clark@example.com',
      categoryID: '6',
      categoryName: 'Gardener',
      totalRating: 4.5,
      totalAgreements: 109,
    },
    {
      uid: 'U014',
      username: 'Noah Taylor',
      profilePic: 'https://randomuser.me/api/portraits/men/7.jpg',
      email: 'noah.taylor@example.com',
      categoryID: '2',
      categoryName: 'Electrician',
      totalRating: 4.5,
      totalAgreements: 156,
    },
    {
      uid: 'U015',
      username: 'Isabella Lewis',
      profilePic: 'https://randomuser.me/api/portraits/women/8.jpg',
      email: 'isabella.lewis@example.com',
      categoryID: '3',
      categoryName: 'Maid',
      totalRating: 4.7,
      totalAgreements: 119,
    },
    {
      uid: 'U016',
      username: 'William Scott',
      profilePic: 'https://randomuser.me/api/portraits/men/8.jpg',
      email: 'william.scott@example.com',
      categoryID: '4',
      categoryName: 'Home Tutor',
      totalRating: 4.9,
      totalAgreements: 180,
    },
    {
      uid: 'U017',
      username: 'Emily Walker',
      profilePic: 'https://randomuser.me/api/portraits/women/9.jpg',
      email: 'emily.walker@example.com',
      categoryID: '5',
      categoryName: 'Painter',
      totalRating: 4.6,
      totalAgreements: 143,
    },
    {
      uid: 'U019',
      username: 'Charlotte King',
      profilePic: 'https://randomuser.me/api/portraits/women/10.jpg',
      email: 'charlotte.king@example.com',
      categoryID: '1',
      categoryName: 'Plumber',
      totalRating: 4.7,
      totalAgreements: 122,
    },
    {
      uid: 'U020',
      username: 'Henry Allen',
      profilePic: 'https://randomuser.me/api/portraits/men/10.jpg',
      email: 'henry.allen@example.com',
      categoryID: '2',
      categoryName: 'Electrician',
      totalRating: 4.8,
      totalAgreements: 135,
    },
    {
      uid: 'U021',
      username: 'Amelia Wright',
      profilePic: 'https://randomuser.me/api/portraits/women/11.jpg',
      email: 'amelia.wright@example.com',
      categoryID: '3',
      categoryName: 'Maid',
      totalRating: 4.9,
      totalAgreements: 178,
    },
  ];
  